# this is just for running it locally
version: '3'
services:
  frontend:
    build:
      context: ./game-bin/frontend
      dockerfile: ../../Dockerfile.frontend
    platform: linux/amd64
    ports:
      - 8080:80
  
  backend:
    build:
      context: ./game-bin/backend
      dockerfile: ../../Dockerfile.backend
    mem_limit: 256M
    stop_signal: kill
    platform: linux/amd64
    depends_on:
    - uahv
    environment:
      - UAHV_ADDR=http://uahv:8083
      - PORT=7778
  
  uahv:
    image: ghcr.io/ultimatetournament/uahv:latest
    platform: linux/amd64
    environment:
      - ENV=LOCAL

  # tcpdump:
  #   scale: 0
  #   image: naqvis/alpine-debug
  #   command: tcpdump -i any -w /dump/dmp port 8080 or port 7778
  #   network_mode: host
  #   privileged: true
  #   volumes:
  #     - ./dump:/dump
